### ISSUE TITLE
Can't find board 'svlinky'

### ISSUE THREAD

**Issue by antskelton42** [sadekbaroudi/zmk-fingerpunch-controllers#1]
I cloned the zmk-ardux (https://github.com/arduxio/zmk-ardux) repo to use as my zmk-config and updated the config/west.yml as directed:

```
manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: zmk-ardux
      url-base: https://github.com/arduxio
    - name: sadekbaroudi
      url-base: https://github.com/sadekbaroudi
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: 8c6bda260ace119b3c22a21bdcdd6d17a83fc5eb
      import: app/west.yml
    - name: zmk-fingerpunch-controllers
      remote: sadekbaroudi
      revision: main
      import: config/deps.yml
  self:
    path: config
```

when I try to build, the board is not recognised:

```
 west build --pristine -b svlinky -- -DSHIELD=the_paintbrush_left -DZMK_CONFIG="/workspaces/zmk-config/config"
```

![image](https://github.com/user-attachments/assets/151c7e92-4292-4b25-8486-9bef40f60865)
