### ISSUE TITLE
Firmware unresponsive

### ISSUE THREAD

**Issue by blowback** [sadekbaroudi/zmk-fingerpunch-controllers#2]
Hi!

I flashed a svlinky 0.2 with a config from here https://github.com/arduxio/zmk-ardux.git editing its config/west.yml to:

```
manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: zmk-ardux
      url-base: https://github.com/arduxio
    - name: sadekbaroudi
      url-base: https://github.com/sadekbaroudi
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: 8c6bda260ace119b3c22a21bdcdd6d17a83fc5eb
      import: app/west.yml
    - name: zmk-fingerpunch-controllers
      remote: sadekbaroudi
      revision: main
      import: config/deps.yml
  self:
    path: config
```

I'm building a "Paintbrush" 8 key keyboard, and this is, I think, an older config intended for Arduino pro micro controllers so I changed the_paintbrush_left.overlay to:

```
/*
 * Copyright (c) 2021 Mike "KemoNine" Crosson
 *
 * SPDX-License-Identifier: MIT
 */

#include <dt-bindings/zmk/matrix_transform.h>

&pro_micro_i2c {
	status = "okay";

	oled: ssd1306@3c {
		compatible = "solomon,ssd1306fb";
		reg = <0x3c>;
		label = "DISPLAY";
		width = <128>;
		height = <32>;
		segment-offset = <0>;
		page-offset = <0>;
		display-offset = <0>;
		multiplex-ratio = <31>;
		segment-remap;
		com-invdir;
		com-sequential;
		prechargep = <0x22>;
		inversion-on;
	};
};

/ {
	chosen {
		zmk,kscan = &kscan0;
		zephyr,display = &oled;
	};

	kscan0: kscan_0 {
		compatible = "zmk,kscan-gpio-direct";

		label = "KSCAN";

		input-gpios
			= <&pro_micro 18 (GPIO_ACTIVE_LOW | GPIO_PULL_UP)>
            , <&pro_micro 19 (GPIO_ACTIVE_LOW | GPIO_PULL_UP)>
            , <&pro_micro 20 (GPIO_ACTIVE_LOW | GPIO_PULL_UP)>
            , <&pro_micro 21 (GPIO_ACTIVE_LOW | GPIO_PULL_UP)>
            , <&pro_micro 10 (GPIO_ACTIVE_LOW | GPIO_PULL_UP)>
            , <&pro_micro 16 (GPIO_ACTIVE_LOW | GPIO_PULL_UP)>
            , <&pro_micro 14 (GPIO_ACTIVE_LOW | GPIO_PULL_UP)>
            , <&pro_micro 15 (GPIO_ACTIVE_LOW | GPIO_PULL_UP)>
            ;
	};
};
```

The difference is basically mapping the 8 keys to different GPIOs, to match those in your sparkfun_pro_micro.dtsi:

![image](https://github.com/user-attachments/assets/0a642535-989a-4faa-adc2-ab91a5db28bf)

I then build this with:

```
west build -p -b svlinky@0.2 -- -DSHIELD=the_paintbrush_left -DZMK_CONFIG=$D/zmk-ardux/config
```
which successfully produces a zmk.uf2 board. If I drag this on to the RPi mount the device reboots, and then is dead - does not USB enumerate. I have to short the boot pins and reset->gnd to recover the device.

I tried adding debug:

```
west build -p -b svlinky@0.2 -- -DSHIELD=the_paintbrush_left -DZMK_CONFIG=$D/zmk-ardux/config -Szmk-usb-logging
```

but the behaviour was the same.

Is there anything else I can try to diagnose the issue? Is there a known-good svlinky firmware that might work (in part) with my 8 key keyboard?
